puts "Ruby on Rails es un framework MVC para aplicaciones web en Ruby."
puts "Ventajas:"
puts "- Alta productividad por convenciones, scaffolds y generadores."
puts "- Ecosistema maduro de gems y comunidad."
puts "- Active Record simplifica el acceso a bases de datos."
puts "- Estructura clara con migraciones y pruebas integradas."
puts "Desventajas:"
puts "- Curva de aprendizaje de convenciones y 'magia'."
puts "- Rendimiento menor en escenarios extremos frente a stacks minimalistas."
puts "- Acoplamiento a Active Record puede limitar ciertos patrones."
puts "- Actualizaciones mayores pueden requerir trabajo de migración."
